// Mocks generated by Mockito 5.4.5 from annotations
// in palm_book/test/data/repositories/book_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:palm_book/core/errors/response_error.dart' as _i5;
import 'package:palm_book/data/datasource/remotes/book_remote_source.dart'
    as _i3;
import 'package:palm_book/data/model/dto/book_model_dto.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRemoteSource extends _i1.Mock implements _i3.BookRemoteSource {
  MockBookRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.ResponseException, List<_i6.BookModelDto>>> getBooks({
    required int? page,
    required String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooks,
          [],
          {
            #page: page,
            #search: search,
          },
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.ResponseException, List<_i6.BookModelDto>>>.value(
            _FakeEither_0<_i5.ResponseException, List<_i6.BookModelDto>>(
          this,
          Invocation.method(
            #getBooks,
            [],
            {
              #page: page,
              #search: search,
            },
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.ResponseException, List<_i6.BookModelDto>>>);

  @override
  _i4.Future<_i2.Either<_i5.ResponseException, _i6.BookModelDto>> getBook(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBook,
          [id],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.ResponseException, _i6.BookModelDto>>.value(
            _FakeEither_0<_i5.ResponseException, _i6.BookModelDto>(
          this,
          Invocation.method(
            #getBook,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ResponseException, _i6.BookModelDto>>);
}
